$('#owl-carousel-1').owlCarousel({
    loop:true,
    margin:10,
    autoplay:true,
    nav:false,
    responsive:{
        0:{
            items:1
        }
    }
})

$('#owl-carousel-2').owlCarousel({
    loop:true,
    margin:15,
    autoplay:true,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        768:{
            items:2
        },
        1024:{
            items:3
        }
    }
})

$('#owl-carousel-3').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        768:{
            items:3
        },
        1024:{
            items:6
        }
    }
})

AOS.init();